// Generated by gencpp from file robot_tracker/VestData.msg
// DO NOT EDIT!


#ifndef ROBOT_TRACKER_MESSAGE_VESTDATA_H
#define ROBOT_TRACKER_MESSAGE_VESTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace robot_tracker
{
template <class ContainerAllocator>
struct VestData_
{
  typedef VestData_<ContainerAllocator> Type;

  VestData_()
    : x_center()
    , y_center()
    , area()
    , rotation_angle()
    , cam_height()
    , cam_width()  {
    }
  VestData_(const ContainerAllocator& _alloc)
    : x_center(_alloc)
    , y_center(_alloc)
    , area(_alloc)
    , rotation_angle(_alloc)
    , cam_height(_alloc)
    , cam_width(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _x_center_type;
  _x_center_type x_center;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _y_center_type;
  _y_center_type y_center;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _area_type;
  _area_type area;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _rotation_angle_type;
  _rotation_angle_type rotation_angle;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _cam_height_type;
  _cam_height_type cam_height;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _cam_width_type;
  _cam_width_type cam_width;





  typedef boost::shared_ptr< ::robot_tracker::VestData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tracker::VestData_<ContainerAllocator> const> ConstPtr;

}; // struct VestData_

typedef ::robot_tracker::VestData_<std::allocator<void> > VestData;

typedef boost::shared_ptr< ::robot_tracker::VestData > VestDataPtr;
typedef boost::shared_ptr< ::robot_tracker::VestData const> VestDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tracker::VestData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tracker::VestData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_tracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_tracker': ['/home/dev/robot/src/robot_tracker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_tracker::VestData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tracker::VestData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tracker::VestData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tracker::VestData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tracker::VestData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tracker::VestData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tracker::VestData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd3cd6db93142c19287d94b60eb73095";
  }

  static const char* value(const ::robot_tracker::VestData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd3cd6db93142c19ULL;
  static const uint64_t static_value2 = 0x287d94b60eb73095ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tracker::VestData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tracker/VestData";
  }

  static const char* value(const ::robot_tracker::VestData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tracker::VestData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 x_center\n\
std_msgs/Float32 y_center\n\
std_msgs/Float32 area\n\
std_msgs/Float32 rotation_angle\n\
std_msgs/Float32 cam_height\n\
std_msgs/Float32 cam_width\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::robot_tracker::VestData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tracker::VestData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_center);
      stream.next(m.y_center);
      stream.next(m.area);
      stream.next(m.rotation_angle);
      stream.next(m.cam_height);
      stream.next(m.cam_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VestData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tracker::VestData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tracker::VestData_<ContainerAllocator>& v)
  {
    s << indent << "x_center: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.x_center);
    s << indent << "y_center: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.y_center);
    s << indent << "area: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.area);
    s << indent << "rotation_angle: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation_angle);
    s << indent << "cam_height: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.cam_height);
    s << indent << "cam_width: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.cam_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TRACKER_MESSAGE_VESTDATA_H
